using System.Text;
using DeckForge.Core.Code;

namespace DeckForge.CodeGen.Generation;

/// <summary>Everything the Actions designer collects, in a form the generator can render.</summary>
public sealed record ActionDesign
{
    public required string ActionId { get; init; }
    public required string ActionName { get; init; }
    public string ActionDescription { get; init; } = "";
    public IReadOnlyList<ActionParameterSpec> Parameters { get; init; } = [];

    /// <summary>The integration class name, derived from the id.</summary>
    public string ClassName => CSharpCode.ToPascal(ActionId) + "Action";

    /// <summary>The resx group every string for this action lives under.</summary>
    public string StringsRoot => ResxKeyBuilder.Build("Actions", CSharpCode.ToPascal(ActionId));

    /// <summary>Problems that would make the output not compile, or not work.</summary>
    public IReadOnlyList<string> Validate()
    {
        var problems = new List<string>();
        if (!Core.Utils.MacroDeckRules.IsValidLocalId(ActionId))
        {
            problems.Add($"Action id '{ActionId}' must be lowercase kebab-case and at most 64 characters.");
        }

        if (Parameters.Count == 0)
        {
            problems.Add("An action needs at least one parameter, or it cannot be configured.");
        }

        var seen = new HashSet<string>(StringComparer.Ordinal);
        foreach (var parameter in Parameters)
        {
            // The name is the wire identity: the host persists it and every existing button that
            // uses this action keeps referring to it. MDP1002 enforces the grammar at build time
            // too, but a clear message beats a squiggle.
            if (!Core.Utils.MacroDeckRules.IsValidLocalId(parameter.Name))
            {
                problems.Add($"Parameter name '{parameter.Name}' must be lowercase kebab-case; it is the persisted wire name.");
            }

            if (!seen.Add(parameter.Name))
            {
                problems.Add($"Parameter name '{parameter.Name}' is used twice.");
            }

            if (!ActionParameterTypes.IsKnown(parameter.EditorType))
            {
                problems.Add($"Unknown editor type '{parameter.EditorType}'.");
            }
        }

        return problems;
    }
}

/// <summary>
/// Emits an <c>IActionDefinition</c> that compiles against the real
/// <c>MacroDeck.Sdk.Actions</c> surface.
/// </summary>
/// <remarks>
/// Every emitted argument after the parameter name is passed by name. C# binds named arguments
/// first and then fills the remainder positionally in declaration order, so a positional argument
/// for an optional parameter silently steals the slot of whatever follows it.
/// </remarks>
public static class ActionGenerator
{
    /// <summary>Renders the action class.</summary>
    public static string Render(ActionDesign design, string @namespace)
    {
        var problems = design.Validate();
        if (problems.Count > 0)
        {
            throw new GenerationException(string.Join(" ", problems));
        }

        var className = design.ClassName;
        var stem = CSharpCode.ToPascal(design.ActionId);
        var root = design.StringsRoot;
        var sb = new StringBuilder();

        sb.AppendLine("using MacroDeck.Localization;");
        sb.AppendLine("using MacroDeck.Sdk;");
        sb.AppendLine("using MacroDeck.Sdk.Actions;");
        sb.AppendLine("using Serilog;");
        sb.AppendLine();
        sb.AppendLine($"namespace {CSharpCode.Identifier(@namespace)};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// {CSharpCode.Xml(design.ActionName)} - generated by DeckForge's Actions editor.");
        sb.AppendLine("/// The parameter plumbing is complete; replace the body of ExecuteAsync with the real work.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public sealed class {className} : IActionDefinition");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly ILogger _logger;");
        sb.AppendLine();
        sb.AppendLine($"    public {className}(ILogger logger) => _logger = logger.ForContext<{className}>();");
        sb.AppendLine();
        sb.AppendLine($"    public string Id => {CSharpCode.StringLiteral(design.ActionId)};");
        sb.AppendLine();
        sb.AppendLine($"    public LocalizedText Name => {ResxKeyBuilder.Accessor(root, "Name")};");
        sb.AppendLine();
        sb.AppendLine($"    public LocalizedText Description => {ResxKeyBuilder.Accessor(root, "Description")};");
        sb.AppendLine();
        sb.AppendLine("    public IReadOnlyList<ActionParameter> Parameters { get; } =");
        sb.AppendLine("    [");

        foreach (var parameter in design.Parameters)
        {
            // Parameters live under their own `Parameters` group, so a parameter called "Name" or
            // "Description" cannot be both a leaf and the group its siblings nest under, which
            // is the SDK's MDLOC008 and a CS0102 in the generated Strings class.
            var key = ResxKeyBuilder.Build(root, "Parameters", parameter.Name);
            var call = ActionParameterFactory.Emit(parameter, property => $"Strings.{key}.{property}()");

            if (!string.IsNullOrWhiteSpace(parameter.OnlyWhenParameter))
            {
                call += $".OnlyWhen({CSharpCode.StringLiteral(parameter.OnlyWhenParameter)}, {CSharpCode.StringLiteral(parameter.OnlyWhenValue)})";
            }

            sb.AppendLine($"        {call},");
        }

        sb.AppendLine("    ];");
        sb.AppendLine();
        sb.AppendLine("    public MacroDeckPlatform Platforms => MacroDeckPlatform.All;");
        sb.AppendLine();
        sb.AppendLine("    public IActionExecutor CreateExecutor() => new Executor(_logger);");
        sb.AppendLine();
        sb.AppendLine("    private sealed class Executor : IActionExecutor");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly ILogger _logger;");
        sb.AppendLine("        private readonly MacroDeck.Sdk.IIntegrationContext? _integration;");
        sb.AppendLine();
        sb.AppendLine("        public Executor(ILogger logger, MacroDeck.Sdk.IIntegrationContext? integration = null)");
        sb.AppendLine("        {");
        sb.AppendLine("            _logger = logger;");
        sb.AppendLine("            _integration = integration;");
        sb.AppendLine("        }");
        sb.AppendLine();

        // async unconditionally, so a later Blocks save that injects an await - Task.Delay, an
        // HTTP call, a folder change - cannot land a bare await in a non-async method.
        sb.AppendLine("        public async Task<ActionResult> ExecuteAsync(ActionExecutionContext context)");
        sb.AppendLine("        {");
        sb.AppendLine("            // TODO: implement the real work. The configured values are:");
        foreach (var parameter in design.Parameters)
        {
            var local = CSharpCode.Identifier(parameter.Name);
            var key = CSharpCode.StringLiteral(parameter.Name);
            sb.AppendLine($"            //     {key} -> context.Parameters.TryGetValue({key}, out var {local});");
        }

        sb.AppendLine("            //");
        sb.AppendLine("            // Parameters is IReadOnlyDictionary<string, object>, so a value is never null.");
        sb.AppendLine("            // Narrow it yourself: `value as string`, Convert.ToDouble(value, ...), and so on.");
        sb.AppendLine("            //");
        sb.AppendLine("            // _integration is the IIntegrationContext captured in InitializeAsync. Deck,");
        sb.AppendLine("            // Notifications, Widgets, Variables, Scripts, Events and Messages live there,");
        sb.AppendLine("            // not on ActionExecutionContext.");
        sb.AppendLine("            //");
        sb.AppendLine("            // context.CancellationToken is already cancelled when the flow is aborted, so");
        sb.AppendLine("            // forward it to anything that can wait (MDP3001).");
        sb.AppendLine("            await Task.CompletedTask;");
        sb.AppendLine();
        sb.AppendLine($"            _logger.Information(\"Action {CSharpCode.EscapeLiteralBody(design.ActionId)} executed\");");
        sb.AppendLine("            return ActionResult.Success();");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>The resx entries the generated code references.</summary>
    public static IReadOnlyDictionary<string, string> BuildStrings(ActionDesign design)
    {
        var root = design.StringsRoot;
        var entries = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            [ResxKeyBuilder.Build(root, "Name")] = design.ActionName,
            [ResxKeyBuilder.Build(root, "Description")] = design.ActionDescription,
        };

        foreach (var parameter in design.Parameters)
        {
            var key = ResxKeyBuilder.Build(root, "Parameters", parameter.Name);
            entries[$"{key}.Label"] = parameter.Label;
            if (!string.IsNullOrWhiteSpace(parameter.Description))
            {
                entries[$"{key}.Description"] = parameter.Description;
            }

            if (!string.IsNullOrWhiteSpace(parameter.Placeholder))
            {
                entries[$"{key}.Placeholder"] = parameter.Placeholder;
            }
        }

        return entries;
    }

    /// <summary>Renders the action and the strings it needs, as one unit.</summary>
    public static GeneratedFile Generate(ActionDesign design, string projectName)
    {
        return GeneratedFile.WithStrings(
            $"{design.ClassName}.cs",
            Render(design, projectName),
            BuildStrings(design));
    }
}
