using System.Text;
using DeckForge.Core.Blocks;

namespace DeckForge.CodeGen.Generation;

/// <summary>
/// Compiles a <see cref="BlockProgram"/> into the C# body of
/// IActionExecutor.ExecuteAsync, wrapped in <c>// &lt;macrodeck-blocks&gt;</c> markers so
/// hand edits outside the markers survive regeneration and the canvas can re-read its own.
/// Generated code honors context.CancellationToken everywhere (MDP3001 discipline).
/// </summary>
public static class BlockCompiler
{
    public const string BeginMarker = "// <macrodeck-blocks>";
    public const string EndMarker = "// </macrodeck-blocks>";

    public static string Compile(BlockProgram program)
    {
        var sb = new StringBuilder();
        sb.AppendLine(BeginMarker);
        sb.AppendLine("// Generated by DeckForge block programmer. Edit on the Blocks canvas;");
        sb.AppendLine("// anything outside these markers is yours and is preserved.");

        var locals = new List<string>();
        foreach (var statement in program.Statements)
        {
            Emit(statement, sb, locals, indent: 1);
        }

        sb.AppendLine(EndMarker);
        return sb.ToString();
    }

    /// <summary>Extracts the marker-wrapped region from a C# file body, if present.</summary>
    public static string? ExtractRegion(string csharpSource)
    {
        var begin = csharpSource.IndexOf(BeginMarker, StringComparison.Ordinal);
        var end = csharpSource.IndexOf(EndMarker, StringComparison.Ordinal);
        if (begin < 0 || end < 0 || end < begin)
        {
            return null;
        }
        return csharpSource[(begin + BeginMarker.Length)..end].Trim();
    }

    private static void Emit(BlockStatement statement, StringBuilder sb, List<string> locals, int indent)
    {
        var pad = new string(' ', indent * 4);
        switch (statement)
        {
            case LogBlock log:
                if (log.Parameter is not null)
                {
                    sb.AppendLine($"{pad}_logger.Information(\"{Escape(log.Template)}\", {Sanitize(log.Parameter)});");
                }
                else
                {
                    sb.AppendLine($"{pad}_logger.Information(\"{Escape(log.Template)}\");");
                }
                break;

            case SetVariableBlock set:
            {
                var name = Sanitize(set.VariableName);
                if (set.FromParameter is not null)
                {
                    var param = Sanitize(set.FromParameter);
                    var cast = set.Type switch
                    {
                        "number" => "Convert.ToDouble(value, System.Globalization.CultureInfo.InvariantCulture)",
                        "bool" => "value is true",
                        _ => "value?.ToString()",
                    };
                    sb.AppendLine($"{pad}var {name} = context.Parameters.TryGetValue(\"{param}\", out var value) ? {cast} : null;");
                    if (set.Type == "string")
                    {
                        sb.AppendLine($"{pad}if (string.IsNullOrWhiteSpace({name}))");
                        sb.AppendLine($"{pad}{{");
                        sb.AppendLine($"{pad}    return ActionResult.Failed(ActionErrorCodes.InvalidParameter, \"Parameter {param} is required.\");");
                        sb.AppendLine($"{pad}}}");
                    }
                }
                else
                {
                    var literal = set.Type == "number" ? set.Literal ?? "0"
                        : set.Type == "bool" ? set.Literal ?? "false"
                        : $"\"{Escape(set.Literal ?? "")}\"";
                    sb.AppendLine($"{pad}var {name} = {literal};");
                }
                break;
            }

            case IfBlock ifBlock:
            {
                var left = Sanitize(ifBlock.LeftVariable);
                var op = ifBlock.Operator switch
                {
                    "==" => "==",
                    "!=" => "!=",
                    ">" => ">",
                    "<" => "<",
                    ">=" => ">=",
                    "<=" => "<=",
                    "isEmpty" => "string.IsNullOrEmpty",
                    "isNotEmpty" => "!string.IsNullOrEmpty",
                    _ => "==",
                };
                if (ifBlock.Operator is "isEmpty" or "isNotEmpty")
                {
                    sb.AppendLine($"{pad}if ({op}({left}))");
                }
                else
                {
                    sb.AppendLine($"{pad}if ({left} {op} \"{Escape(ifBlock.RightLiteral ?? "")}\")");
                }
                sb.AppendLine($"{pad}{{");
                foreach (var child in ifBlock.Then)
                {
                    Emit(child, sb, locals, indent + 1);
                }
                sb.AppendLine($"{pad}}}");
                break;
            }

            case ReturnResultBlock ret:
                switch (ret.Outcome)
                {
                    case "failed":
                        sb.AppendLine($"{pad}return ActionResult.Failed(ActionErrorCodes.{ret.ErrorCode ?? "ProviderError"}, \"{Escape(ret.Message)}\");");
                        break;
                    case "accepted":
                        sb.AppendLine($"{pad}return ActionResult.Accepted(\"{Escape(ret.Message)}\");");
                        break;
                    default:
                        sb.AppendLine($"{pad}return ActionResult.Success();");
                        break;
                }
                break;

            case DelayBlock delay:
                sb.AppendLine($"{pad}await Task.Delay({delay.Milliseconds}, context.CancellationToken);");
                break;

            case HttpRequestBlock http:
            {
                var name = Sanitize(http.IntoVariable);
                sb.AppendLine($"{pad}using var client = new System.Net.Http.HttpClient();");
                sb.AppendLine($"{pad}var {name} = await client.GetStringAsync(\"{Escape(http.Url)}\", context.CancellationToken);");
                break;
            }

            case NotifyBlock notify:
                sb.AppendLine($"{pad}context.Notifications?.Notify(\"{Escape(notify.Title)}\", \"{Escape(notify.Message)}\");");
                break;

            case NavigateBlock navigate:
                sb.AppendLine($"{pad}context.Deck?.OpenFolder(\"{Escape(navigate.FolderId)}\", context.OriginClientId);");
                break;

            default:
                sb.AppendLine($"{pad}// unsupported block");
                break;
        }
    }

    private static string Sanitize(string name)
    {
        var chars = name.Select(c => char.IsAsciiLetterOrDigit(c) ? c : '_').ToArray();
        var safe = new string(chars);
        return char.IsAsciiDigit(safe[0]) ? "_" + safe : safe;
    }

    private static string Escape(string s) => s
        .Replace("\\", "\\\\")
        .Replace("\"", "\\\"");
}
