namespace DeckForge.CodeGen.Generation;

/// <summary>
/// The source of the generated <c>VisualRuntime.cs</c> support file (Part 8.4).
/// </summary>
/// <remarks>
/// <para>
/// Scratch semantics need helpers that raw SDK calls cannot express: loose coercion, timers, polling,
/// request-scoped state. One generated file per plugin carries them, so a block's emission stays one
/// readable line and the plugin's method is not buried under conversion noise.
/// </para>
/// <para>
/// <see cref="VisualEmitterTests"/> cross-checks this template's public surface against every
/// <c>VisualRuntime.*</c> call the block catalog's templates make — an emitter cannot name a helper
/// that does not exist, and the test fails naming the missing one.
/// </para>
/// </remarks>
public static class VisualRuntimeTemplate
{
    public const string FileName = "VisualRuntime.cs";
    /// <summary>
    /// The runtime file's text for a plugin's root namespace.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The literal carries <c>__NAMESPACE__</c> rather than a namespace, because one source has to serve
    /// every plugin. Substituting it is the whole of <c>Render</c>, and it is the only place that is
    /// allowed to: writing the literal out verbatim produced a file whose <c>namespace __NAMESPACE__;</c>
    /// declaration named a namespace nothing declared, and every region referencing <c>VisualRuntime</c>
    /// then failed with CS0103 - in a generated plugin nobody had built yet, because no part of this
    /// project built a generated plugin by default.
    /// </para>
    /// <para>
    /// Internal, deliberately. A plugin's runtime file belongs to the plugin, so the caller that writes it
    /// is the one that knows the namespace; handing the constant out invites exactly the mistake above.
    /// </para>
    /// </remarks>
    public static string Render(string rootNamespace)
    {
        if (string.IsNullOrWhiteSpace(rootNamespace))
        {
            throw new ArgumentException("A plugin namespace is required.", nameof(rootNamespace));
        }

        return Source.Replace("__NAMESPACE__", rootNamespace, StringComparison.Ordinal);
    }

    public const string Source = """
        // <auto-generated by DeckForge. Edits are overwritten.>
        using System;
        using System.Collections.Generic;
        using System.Diagnostics;
        using System.IO;
        using System.Linq;
        using System.Threading;
        using System.Threading.Tasks;
        using MacroDeck.Sdk;

        namespace __NAMESPACE__;

        /// <summary>
        /// Runtime helpers for scripts written in DeckForge's Visual editor.
        /// </summary>
        internal static class VisualRuntime
        {
            private static readonly Stopwatch Uptime = Stopwatch.StartNew();
            private static readonly Stopwatch Invocation = Stopwatch.StartNew();
            private static readonly Stopwatch LastRequest = Stopwatch.StartNew();
            private static bool lastRequestFailed;
            private static string? bearerTokenParameter;

            /// <summary>The request-scoped state one invocation's scripts share.</summary>
            internal static readonly Dictionary<string, object?> Locals = new(StringComparer.Ordinal);

            /// <summary>Names shown in the debugger's watch table.</summary>
            internal static readonly System.Collections.Generic.List<string> Watched = new System.Collections.Generic.List<string>();

            public static double ElapsedSeconds() => Invocation.Elapsed.TotalSeconds;

            public static void ResetTimer() => Invocation.Restart();

            public static double UptimeSeconds() => Uptime.Elapsed.TotalSeconds;

            public static void Watch(string name)
            {
                if (!Watched.Contains(name, StringComparer.Ordinal)) Watched.Add(name);
            }

            public static void Unwatch(string name) => Watched.Remove(name);

            public static void ClearLocals() => Locals.Clear();

            public static void Set(string name, object? value) => Locals[name] = value;

            public static object? Get(string name) => Locals.TryGetValue(name, out var value) ? value : null;

            public static void Change(string name, object? amount)
            {
                var current = ToNumber(Get(name));
                var delta = ToNumber(amount);
                Set(name, current + delta);
            }

            public static string ToText(object? value) => value switch
            {
                null => string.Empty,
                string s => s,
                bool b => b ? "true" : "false",
                double d => d.ToString("R", System.Globalization.CultureInfo.InvariantCulture),
                float f => f.ToString("R", System.Globalization.CultureInfo.InvariantCulture),
                decimal m => m.ToString(System.Globalization.CultureInfo.InvariantCulture),
                System.Text.Json.JsonElement { ValueKind: System.Text.Json.JsonValueKind.String } e => e.GetString() ?? string.Empty,
                System.Text.Json.JsonElement { ValueKind: System.Text.Json.JsonValueKind.Number } e => e.GetRawText(),
                System.Text.Json.JsonElement { ValueKind: System.Text.Json.JsonValueKind.True } => "true",
                System.Text.Json.JsonElement { ValueKind: System.Text.Json.JsonValueKind.False } => "false",
                _ => value.ToString() ?? string.Empty,
            };

            public static double ToNumber(object? value)
            {
                if (value is null) return 0;
                if (value is double d) return d;
                if (value is int or long or float or decimal or short or byte) return System.Convert.ToDouble(value, System.Globalization.CultureInfo.InvariantCulture);
                if (value is bool b) return b ? 1 : 0;
                return double.TryParse(ToText(value).Trim(), System.Globalization.NumberStyles.Float, System.Globalization.CultureInfo.InvariantCulture, out var parsed) ? parsed : 0;
            }

            public static bool ToBool(object? value) => value switch
            {
                null => false,
                bool b => b,
                double d => d != 0,
                string s => bool.TryParse(s, out var parsed) ? parsed
                    : double.TryParse(s, System.Globalization.NumberStyles.Float, System.Globalization.CultureInfo.InvariantCulture, out var n) ? n != 0
                    : s.Length > 0,
                _ => true,
            };

            public static bool Compare(object? a, string op, object? b)
            {
                switch (op)
                {
                    case "=": return EqualsText(a, b);
                    case "!=": return !EqualsText(a, b);
                    case "<": return ToNumber(a) < ToNumber(b);
                    case ">": return ToNumber(a) > ToNumber(b);
                    case "<=": return ToNumber(a) <= ToNumber(b);
                    case ">=": return ToNumber(a) >= ToNumber(b);
                    case "isEmpty": return ToText(a).Length == 0;
                    case "isNotEmpty": return ToText(a).Length > 0;
                    case "isAvailable": return a is not null;
                    case "isNotAvailable": return a is null;
                    case "contains": return ToText(a).Contains(ToText(b), StringComparison.Ordinal);
                    case "notContains": return !ToText(a).Contains(ToText(b), StringComparison.Ordinal);
                    default: return false;
                }
            }

            private static bool EqualsText(object? a, object? b)
            {
                if (a is string || b is string) return string.Equals(ToText(a), ToText(b), StringComparison.Ordinal);
                if (a is null && b is null) return true;
                if (a is null || b is null) return false;
                if (IsNumeric(a) && IsNumeric(b)) return ToNumber(a).Equals(ToNumber(b));
                if (a is bool || b is bool) return ToBool(a) == ToBool(b);
                return string.Equals(ToText(a), ToText(b), StringComparison.Ordinal);
            }

            private static bool IsNumericCore(object? value) =>
                value is double or int or long or float or decimal or short or byte;

            public static bool IsNumeric(object? value) => IsNumericCore(value);

            public static double Divide(object? a, object? b)
            {
                var divisor = ToNumber(b);
                return divisor == 0 ? 0 : ToNumber(a) / divisor;
            }

            public static double Modulo(object? a, object? b)
            {
                var divisor = ToNumber(b);
                return divisor == 0 ? 0 : ToNumber(a) % divisor;
            }

            public static double Round(object? value) => System.Math.Round(ToNumber(value), System.MidpointRounding.AwayFromZero);

            public static double Math(string fn, object? value)
            {
                var v = ToNumber(value);
                return fn switch
                {
                    "abs" => System.Math.Abs(v),
                    "floor" => System.Math.Floor(v),
                    "ceiling" => System.Math.Ceiling(v),
                    "sqrt" => v < 0 ? 0 : System.Math.Sqrt(v),
                    "sin" => System.Math.Sin(v),
                    "cos" => System.Math.Cos(v),
                    "tan" => System.Math.Tan(v),
                    "asin" => System.Math.Asin(System.Math.Clamp(v, -1, 1)),
                    "acos" => System.Math.Acos(System.Math.Clamp(v, -1, 1)),
                    "atan" => System.Math.Atan(v),
                    "ln" => v <= 0 ? 0 : System.Math.Log(v),
                    "log" => v <= 0 ? 0 : System.Math.Log10(v),
                    "exp" => System.Math.Exp(v),
                    "pow10" => System.Math.Pow(10, v),
                    _ => v,
                };
            }

            public static double Clamp(object? value, object? low, object? high)
            {
                var lo = ToNumber(low);
                var hi = ToNumber(high);
                if (lo > hi) (lo, hi) = (hi, lo);
                return System.Math.Clamp(ToNumber(value), lo, hi);
            }

            private static readonly System.Random RandomSource = new();

            public static double Random(object? from, object? to)
            {
                var lo = (int)System.Math.Round(ToNumber(from));
                var hi = (int)System.Math.Round(ToNumber(to));
                if (lo > hi) (lo, hi) = (hi, lo);
                return RandomSource.Next(lo, hi + 1);
            }

            public static string JoinList(IReadOnlyList<string> list, string separator) => string.Join(separator, list);

            public static string LetterOf(object? index, object? text)
            {
                var s = ToText(text);
                var oneBased = (int)ToNumber(index);
                if (oneBased < 1 || oneBased > s.Length) return string.Empty;
                return s.Substring(oneBased - 1, 1);
            }

            public static string Substring(object? text, object? start, object? length)
            {
                var s = ToText(text);
                var from = (int)ToNumber(start) - 1;
                if (from < 0 || from >= s.Length) return string.Empty;
                var take = System.Math.Min((int)ToNumber(length), s.Length - from);
                return take <= 0 ? string.Empty : s.Substring(from, take);
            }

            public static IReadOnlyList<string> Split(object? text, string separator)
            {
                var value = ToText(text);
                return value.Length == 0 ? [] : value.Split(separator, StringSplitOptions.None);
            }

            public static string Format(string template, string args)
            {
                var parts = args.Replace("\r\n", "\n", StringComparison.Ordinal).Split('\n', StringSplitOptions.RemoveEmptyEntries);
                return string.Format(
                    System.Globalization.CultureInfo.InvariantCulture,
                    template.Replace("{", "{{", StringComparison.Ordinal).Replace("}", "}}", StringComparison.Ordinal),
                    parts);
            }

            public static string Base64Decode(object? text)
            {
                try
                {
                    return System.Text.Encoding.UTF8.GetString(System.Convert.FromBase64String(ToText(text)));
                }
                catch (FormatException)
                {
                    return string.Empty;
                }
            }

            public static string JsonGet(object? text, string path)
            {
                try
                {
                    using var document = System.Text.Json.JsonDocument.Parse(ToText(text));
                    var current = document.RootElement;
                    foreach (var segment in path.Split('.', StringSplitOptions.RemoveEmptyEntries))
                    {
                        if (current.ValueKind == System.Text.Json.JsonValueKind.Object && current.TryGetProperty(segment, out var next))
                        {
                            current = next;
                            continue;
                        }

                        if (current.ValueKind == System.Text.Json.JsonValueKind.Array
                            && int.TryParse(segment, out var index)
                            && index >= 0 && index < current.GetArrayLength())
                        {
                            current = current[index];
                            continue;
                        }

                        return string.Empty;
                    }

                    return ToText(current.Clone());
                }
                catch (System.Text.Json.JsonException)
                {
                    return string.Empty;
                }
            }

            public static IReadOnlyList<string> DecodeJson(object? text)
            {
                try
                {
                    using var document = System.Text.Json.JsonDocument.Parse(ToText(text));
                    var result = new System.Collections.Generic.List<string>();
                    Flatten(document.RootElement, string.Empty, result);
                    return result;
                }
                catch (System.Text.Json.JsonException)
                {
                    return [];
                }
            }

            private static void Flatten(System.Text.Json.JsonElement element, string prefix, System.Collections.Generic.List<string> into)
            {
                switch (element.ValueKind)
                {
                    case System.Text.Json.JsonValueKind.Object:
                        foreach (var property in element.EnumerateObject())
                        {
                            Flatten(property.Value, prefix.Length == 0 ? property.Name : prefix + "." + property.Name, into);
                        }
                        break;
                    case System.Text.Json.JsonValueKind.Array:
                        var index = 0;
                        foreach (var item in element.EnumerateArray())
                        {
                            Flatten(item, prefix + "[" + index++ + "]", into);
                        }
                        break;
                    default:
                        into.Add(prefix.Length == 0 ? ToText(element.Clone()) : prefix + "=" + ToText(element.Clone()));
                        break;
                }
            }

            public static string Parameter(MacroDeck.Sdk.Actions.ActionExecutionContext context, string name, string? fallback = null) =>
                context.Parameters.TryGetValue(name, out var value) && value is not null
                    ? ToText(value)
                    : fallback ?? string.Empty;

            public static bool HasValue(MacroDeck.Sdk.Actions.ActionExecutionContext context, string name) =>
                context.Parameters.TryGetValue(name, out var value) && value is not null && ToText(value).Length > 0;

            public static object? ReadParameter(
                MacroDeck.Sdk.Actions.ActionExecutionContext context, string name, string type, bool required)
            {
                context.Parameters.TryGetValue(name, out var raw);
                if (raw is null || (raw is string s && s.Length == 0))
                {
                    if (required)
                    {
                        throw new InvalidOperationException("Parameter " + name + " is required.");
                    }

                    return type switch
                    {
                        "Numeric" => 0.0,
                        "Boolean" => false,
                        _ => string.Empty,
                    };
                }

                return type switch
                {
                    "Numeric" => ToNumber(raw),
                    "Boolean" => ToBool(raw),
                    _ => ToText(raw),
                };
            }

            public static object? Convert(object? value, string type) => type switch
            {
                "Numeric" => ToNumber(value),
                "Boolean" => ToBool(value),
                _ => ToText(value),
            };

            public static string? DefaultIfEmpty(object? value, string? fallback)
            {
                var text = ToText(value);
                return text.Length == 0 ? fallback : text;
            }

            public static string Current(string part)
            {
                var now = DateTime.Now;
                return part switch
                {
                    "Year" => now.Year.ToString(System.Globalization.CultureInfo.InvariantCulture),
                    "Month" => now.Month.ToString("00", System.Globalization.CultureInfo.InvariantCulture),
                    "Day" => now.Day.ToString("00", System.Globalization.CultureInfo.InvariantCulture),
                    "Weekday" => now.DayOfWeek.ToString(),
                    "Hour" => now.Hour.ToString("00", System.Globalization.CultureInfo.InvariantCulture),
                    "Minute" => now.Minute.ToString("00", System.Globalization.CultureInfo.InvariantCulture),
                    "Second" => now.Second.ToString("00", System.Globalization.CultureInfo.InvariantCulture),
                    "Date" => now.ToString("yyyy-MM-dd", System.Globalization.CultureInfo.InvariantCulture),
                    "Time" => now.ToString("HH:mm:ss", System.Globalization.CultureInfo.InvariantCulture),
                    "Timestamp" => now.ToString("yyyy-MM-dd HH:mm:ss", System.Globalization.CultureInfo.InvariantCulture),
                    "UtcHour" => now.ToUniversalTime().Hour.ToString("00", System.Globalization.CultureInfo.InvariantCulture),
                    "UtcDate" => now.ToUniversalTime().ToString("yyyy-MM-dd", System.Globalization.CultureInfo.InvariantCulture),
                    _ => string.Empty,
                };
            }

            public static string FormatDate(object? value, string pattern) =>
                DateTime.TryParse(ToText(value), System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeStyles.None, out var parsed)
                    ? parsed.ToString(pattern, System.Globalization.CultureInfo.InvariantCulture)
                    : string.Empty;

            public static double SecondsSince(object? value) =>
                DateTime.TryParse(ToText(value), System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeStyles.None, out var parsed)
                    ? (DateTime.Now - parsed).TotalSeconds
                    : 0;

            public static string EntryId(string entryName) => entryName;

            public static string ActionId() => string.Empty;

            public static IReadOnlyList<string> List(IReadOnlyList<string> list) => list;

            public static IReadOnlyList<string> List(IEnumerable<string> items) => items.ToList();

            public static string Item(IReadOnlyList<string> list, object? index)
            {
                var oneBased = (int)ToNumber(index);
                if (oneBased < 1 || oneBased > list.Count) return string.Empty;
                return list[oneBased - 1];
            }

            public static int IndexOf(IReadOnlyList<string> list, object? item)
            {
                var text = ToText(item);
                for (var i = 0; i < list.Count; i++)
                {
                    if (string.Equals(list[i], text, StringComparison.Ordinal)) return i + 1;
                }

                return 0;
            }

            public static string RandomItem(IReadOnlyList<string> list) =>
                list.Count == 0 ? string.Empty : list[RandomSource.Next(list.Count)];

            public static string LogTemplate(string template, IReadOnlyDictionary<string, object> parameters) =>
                System.Text.RegularExpressions.Regex.Replace(
                    template,
                    @"\{([A-Za-z_][A-Za-z0-9_]*)\}",
                    match => parameters.TryGetValue(match.Groups[1].Value, out var value) ? ToText(value) : match.Value);

            public static async System.Threading.Tasks.Task WaitUntilAsync(
                Func<bool> condition, int pollMilliseconds, System.Threading.CancellationToken cancellationToken)
            {
                while (!condition())
                {
                    cancellationToken.ThrowIfCancellationRequested();
                    await System.Threading.Tasks.Task.Delay(pollMilliseconds, cancellationToken);
                }
            }

            public static async System.Threading.Tasks.Task<object?> HostVariableAsync(
                IIntegrationContext integration, string name, System.Threading.CancellationToken cancellationToken)
            {
                try
                {
                    var handle = await integration.Variables.GetByNameAsync(name);
                    return handle?.Value;
                }
                catch (Exception ex) when (ex is KeyNotFoundException or InvalidOperationException)
                {
                    return null;
                }
            }

            public static async System.Threading.Tasks.Task WriteUserVariableAsync(
                IIntegrationContext integration, string name, string? ownerWidgetId,
                MacroDeck.Sdk.Variables.UserVariableOperation operation, string? value,
                System.Threading.CancellationToken cancellationToken)
            {
                await integration.UserVariables.ApplyAsync(
                    name, ownerWidgetId ?? string.Empty, operation, value ?? string.Empty, cancellationToken);
            }

            public static IReadOnlyDictionary<string, object> Parameters(string lines)
            {
                var result = new Dictionary<string, object>(StringComparer.Ordinal);
                foreach (var (name, value) in ParsePairs(lines))
                {
                    result[name] = value;
                }

                return result;
            }

            public static IReadOnlyDictionary<string, System.Text.Json.JsonElement> Data(string lines)
            {
                var result = new Dictionary<string, System.Text.Json.JsonElement>(StringComparer.Ordinal);
                foreach (var (name, value) in ParsePairs(lines))
                {
                    result[name] = System.Text.Json.JsonSerializer.Deserialize<System.Text.Json.JsonElement>(
                        System.Text.Json.JsonSerializer.Serialize(value));
                }

                return result;
            }

            public static System.Text.Json.JsonElement Json(string text) =>
                System.Text.Json.JsonSerializer.Deserialize<System.Text.Json.JsonElement>(
                    string.IsNullOrWhiteSpace(text) ? "{}" : text);

            public static System.Threading.CancellationToken? NoToken() => null;

            // ---- HTTP ------------------------------------------------------------------------------------

            public static void UseBearerToken(string parameterName) => bearerTokenParameter = parameterName;

            public static async System.Threading.Tasks.Task<HttpResponseRecord> HttpAsync(
                string url, string method, string? body, IReadOnlyDictionary<string, string>? headers,
                System.Threading.CancellationToken cancellationToken)
            {
                try
                {
                    using var client = new System.Net.Http.HttpClient();
                    using var request = new System.Net.Http.HttpRequestMessage(new System.Net.Http.HttpMethod(method), url);
                    if (headers is not null)
                    {
                        foreach (var (name, value) in headers)
                        {
                            request.Headers.TryAddWithoutValidation(name, value);
                        }
                    }

                    if (bearerTokenParameter is not null)
                    {
                        request.Headers.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue(
                            "Bearer", bearerTokenParameter);
                    }

                    if (!string.IsNullOrEmpty(body) && method is not "GET" and not "HEAD")
                    {
                        request.Content = new System.Net.Http.StringContent(
                            body, System.Text.Encoding.UTF8, "application/json");
                    }

                    var stopwatch = Stopwatch.StartNew();
                    using var response = await client.SendAsync(request, cancellationToken);
                    var content = await response.Content.ReadAsStringAsync(cancellationToken);
                    lastRequestFailed = !response.IsSuccessStatusCode;
                    return new HttpResponseRecord(
                        content,
                        (int)response.StatusCode,
                        response.IsSuccessStatusCode,
                        response.Headers.ToDictionary(h => h.Key, h => string.Join(", ", h.Value), StringComparer.OrdinalIgnoreCase),
                        stopwatch.ElapsedMilliseconds);
                }
                catch (System.Net.Http.HttpRequestException)
                {
                    lastRequestFailed = true;
                    return new HttpResponseRecord(string.Empty, 0, false, new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase), 0);
                }
                catch (System.Threading.Tasks.TaskCanceledException)
                {
                    lastRequestFailed = true;
                    return new HttpResponseRecord(string.Empty, 0, false, new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase), 0);
                }
            }

            public static async System.Threading.Tasks.Task<HttpResponseRecord> DownloadAsync(
                string url, string path, System.Threading.CancellationToken cancellationToken)
            {
                var record = await HttpAsync(url, "GET", null, null, cancellationToken);
                Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(path))!);
                await File.WriteAllTextAsync(path, record.Body, cancellationToken);
                return record;
            }

            public static async System.Threading.Tasks.Task<HttpResponseRecord> UploadAsync(
                string path, string url, System.Threading.CancellationToken cancellationToken)
            {
                try
                {
                    using var client = new System.Net.Http.HttpClient();
                    using var content = new System.Net.Http.StreamContent(File.OpenRead(path));
                    content.Headers.ContentType = new System.Net.Http.Headers.MediaTypeHeaderValue("application/octet-stream");
                    using var response = await client.PostAsync(url, content, cancellationToken);
                    var responseBody = await response.Content.ReadAsStringAsync(cancellationToken);
                    lastRequestFailed = !response.IsSuccessStatusCode;
                    return new HttpResponseRecord(
                        responseBody, (int)response.StatusCode, response.IsSuccessStatusCode,
                        new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase), 0);
                }
                catch (System.Net.Http.HttpRequestException)
                {
                    lastRequestFailed = true;
                    return new HttpResponseRecord(string.Empty, 0, false, new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase), 0);
                }
            }

            public static bool LastRequestFailed() => lastRequestFailed;

            public static string ResponseBody(HttpResponseRecord record) => record.Body;

            public static int StatusCode(HttpResponseRecord record) => record.StatusCode;

            public static bool IsSuccess(HttpResponseRecord record) => record.IsSuccess;

            public static bool TimedOut(HttpResponseRecord record) => record.ElapsedMilliseconds == 0 && !record.IsSuccess;

            public static string ResponseHeader(HttpResponseRecord record, string name) =>
                record.Headers.TryGetValue(name, out var value) ? value : string.Empty;

            public static async System.Threading.Tasks.Task RegisterAssetAsync(
                IIntegrationContext integration, string name, string path, System.Threading.CancellationToken cancellationToken)
            {
                var bytes = await File.ReadAllBytesAsync(path, cancellationToken);
                await integration.UiResources.RegisterAsync(name, bytes, "application/octet-stream", cancellationToken);
            }

            private static (string Name, string Value)[] ParsePairs(string lines)
            {
                var result = new System.Collections.Generic.List<(string, string)>();
                foreach (var line in lines.Replace("\r\n", "\n", StringComparison.Ordinal).Split('\n'))
                {
                    var trimmed = line.Trim();
                    if (trimmed.Length == 0) continue;
                    var equals = trimmed.IndexOf('=');
                    if (equals <= 0) continue;
                    result.Add((trimmed[..equals].Trim(), trimmed[(equals + 1)..].Trim()));
                }

                return [.. result];
            }
        }

        /// <summary>The result of one HTTP call, read by the response blocks.</summary>
        internal sealed record HttpResponseRecord(
            string Body,
            int StatusCode,
            bool IsSuccess,
            IReadOnlyDictionary<string, string> Headers,
            long ElapsedMilliseconds);
        """;
}
