using DeckForge.Core.Visual;

namespace DeckForge.CodeGen.Generation;

/// <summary>What happened when a visual script was written into its action.</summary>
/// <param name="Success">True when the action source was rewritten.</param>
/// <param name="Content">The rewritten source, or the original when <paramref name="Success"/> is false.</param>
/// <param name="Message">A description a user can act on.</param>
public sealed record VisualWriteResult(bool Success, string Content, string Message)
{
    public static VisualWriteResult Ok(string content, string message = "Visual blocks written.") =>
        new(true, content, message);

    public static VisualWriteResult Failed(string original, string message) => new(false, original, message);
}

/// <summary>
/// Writes a visual script into the action it targets.
/// </summary>
/// <remarks>
/// <para>
/// The visual page's counterpart of <see cref="BlockProgramWriter"/>: same three fallible steps, same
/// result contract, different compiler. The steps are reused rather than re-implemented —
/// <see cref="BlockCompiler.Splice(string, string, string, int)"/> matches the file's own indentation
/// and replaces an existing region in place, and <see cref="BlockCompiler.EnsureAsyncExecutor"/>
/// repairs the stock template's synchronous returns. Re-writing either is how the "wrong on the
/// second save" class of defect was born last time.
/// </para>
/// <para>
/// A document may also declare procedures that this target's script does not call; the emitter hoists
/// only what is referenced, so an unused procedure costs nothing in the generated file.
/// </para>
/// </remarks>
public static class VisualProgramWriter
{
    /// <summary>
    /// The signature the region is spliced into, matched as a substring so it still matches after
    /// the executor has been made async ("public async Task<ActionResult> …" no longer contains the
    /// "public Task&lt;…&gt;" spelling the first save matched).
    /// </summary>
    public const string ExecutorAnchor = "Task<ActionResult> ExecuteAsync(ActionExecutionContext context)";

    /// <summary>
    /// Produces the action source that runs <paramref name="script"/>.
    /// </summary>
    /// <param name="actionSource">The action file's current contents.</param>
    /// <param name="project">The owning document, for procedure lookup.</param>
    /// <param name="script">The script of the document's target to write.</param>
    /// <param name="integrationAvailable">Whether the plugin declares <c>IIntegrationContextAware</c>.</param>
    public static VisualWriteResult Write(
        string actionSource,
        VisualProject project,
        VisualScript script,
        bool integrationAvailable = true)
    {
        var (code, problems) = VisualEmitter.CompileTarget(FindTarget(project, script), project);

        if (code.Trim().Length == 0)
        {
            return VisualWriteResult.Failed(actionSource, "There are no blocks to write.");
        }

        var hostGuarded = code.Contains("_integration", StringComparison.Ordinal);
        if (hostGuarded && !integrationAvailable)
        {
            return VisualWriteResult.Failed(
                actionSource,
                "This plugin has no host integration, so blocks that call the host cannot be written. "
                + "Add the integration capability on the Capabilities page and regenerate.");
        }

        var compiled =
            "// <macrodeck-blocks>\n"
            + "// Generated by DeckForge's Visual editor. Edit on the canvas; anything outside\n"
            + "// these markers is yours and is preserved across regeneration.\n"
            + code.TrimEnd()
            + "\n// </macrodeck-blocks>\n";

        var spliced = BlockCompiler.Splice(actionSource, compiled, ExecutorAnchor);
        if (spliced is null)
        {
            return VisualWriteResult.Failed(
                actionSource,
                $"Could not find `{ExecutorAnchor}` to write the blocks into.");
        }

        spliced = BlockCompiler.EnsureAsyncExecutor(spliced);

        // A document with problems still writes: the canvas shows the findings and the region carries
        // comments where the broken blocks were, so nothing the user built disappears. The message is
        // where the count is reported.
        var message = problems.Count == 0
            ? "Visual blocks written."
            : $"Visual blocks written with {problems.Count} problem(s) to resolve on the canvas.";

        return VisualWriteResult.Ok(spliced, message);
    }

    private static VisualTarget FindTarget(VisualProject project, VisualScript script) =>
        project.Targets.FirstOrDefault(target => target.Scripts.Contains(script))
        ?? new VisualTarget { Id = "action:adhoc", Name = "adhoc", Scripts = [script] };
}
