namespace DeckForge.Core.Visual;

/// <summary>
/// The vocabulary: every block the palette offers, one method per category.
/// </summary>
/// <remarks>
/// <para>
/// Split from <c>BlockCatalog.cs</c> so the rules and the vocabulary can be read separately. Each row's
/// <see cref="SdkMapping.VerifiedAgainst"/> names the Appendix A surface it was read from, which is what
/// makes <see cref="BlockDescriptor.IsVerified"/> a claim with evidence rather than a mood.
/// </para>
/// <para>
/// Expressions are templates: <c>{into}</c>, <c>{level}</c>, <c>{var}</c> and so on are replaced by the
/// emitter with the block's field or slot value.
/// </para>
/// </remarks>
public static partial class BlockCatalog
{
    private static IReadOnlyList<BlockDescriptor> ControlRows() =>
    [
        Hat("hat.action-runs", BlockCategory.Control, "when action runs",
            "The action executor's entry point. One per action target.",
            "IActionExecutor.ExecuteAsync"),
        Hat("hat.script-starts", BlockCategory.Control, "when script starts",
            "A script that nothing but a call reaches.",
            "plain C# (reached only by call)"),

        Stack("control.wait-seconds", BlockCategory.Control, "wait {seconds} seconds",
            "Pauses, honouring cancellation.", Plain("await Task.Delay((int)(VisualRuntime.ToNumber(seconds) * 1000), context.CancellationToken);"),
            [Num("seconds", def: "1")]),
        Stack("control.wait-ms", BlockCategory.Control, "wait {ms} ms",
            "Pauses for a number of milliseconds.", Plain("await Task.Delay((int)VisualRuntime.ToNumber(ms), context.CancellationToken);"),
            [Num("ms", def: "500")]),
        Stack("control.wait-until", BlockCategory.Control, "wait until {condition}",
            "Polls a condition, honouring cancellation.",
            Plain("await VisualRuntime.WaitUntilAsync(() => VisualRuntime.ToBool({condition}), 50, context.CancellationToken);"),
            [Bool("condition")]),

        Container("control.repeat", BlockCategory.Control, "repeat {count}",
            "Runs the body a number of times.",
            Plain("for (var _i = 0; _i < (int)VisualRuntime.ToNumber(count); _i++)\n{\n    context.CancellationToken.ThrowIfCancellationRequested();"),
            [Num("count", def: "10")], bodies: [Body("body", "repeat")]),
        Container("control.repeat-until", BlockCategory.Control, "repeat until {condition}",
            "Runs the body, then tests: the body always runs at least once.",
            Plain("do\n{"),
            [Bool("condition")], bodies: [Body("body", "until")]),
        Container("control.forever", BlockCategory.Control, "forever",
            "Runs the body until the action is cancelled.",
            Plain("while (true)\n{\n    context.CancellationToken.ThrowIfCancellationRequested();"),
            bodies: [Body("body", "forever")]),
        Container("control.while", BlockCategory.Control, "while {condition}",
            "Tests first, then runs the body.",
            Plain("while (VisualRuntime.ToBool({condition}))\n{\n    context.CancellationToken.ThrowIfCancellationRequested();"),
            [Bool("condition")], bodies: [Body("body", "while")]),

        Container("control.if", BlockCategory.Control, "if {condition}",
            "Runs the body when the condition is true.",
            Plain("if (VisualRuntime.ToBool({condition}))"),
            [Bool("condition")], bodies: [Body("then", "then")]),
        Container("control.if-else", BlockCategory.Control, "if {condition} else",
            "Runs one of two bodies.",
            Plain("if (VisualRuntime.ToBool({condition}))"),
            [Bool("condition")], bodies: [Body("then", "then"), Body("else", "else")]),
        Container("control.if-else-if", BlockCategory.Control, "if {condition} else if {condition2}",
            "Two conditions with an optional final else.",
            Plain("if (VisualRuntime.ToBool({condition}))"),
            [Bool("condition"), Bool("condition2", required: false)],
            bodies: [Body("then", "then"), Body("elseIf", "else if"), Body("else", "else")]),

        Stack("control.break", BlockCategory.Control, "break",
            "Leaves the nearest enclosing loop.", Plain("break;")),
        Stack("control.continue", BlockCategory.Control, "continue",
            "Skips to the next iteration of the nearest loop.", Plain("continue;")),
        Stack("control.yield", BlockCategory.Control, "yield to host",
            "Gives the host a turn without ending the action.", Plain("await Task.Yield();")),

        Cap("control.stop-script", BlockCategory.Control, "stop this script",
            "Ends the script, reporting success.", Plain("return ActionResult.Success();", "ActionResult.Success")),
        Cap("control.stop-all", BlockCategory.Control, "stop all scripts",
            "Ends the action and everything left in it.",
            Plain("return ActionResult.Success();", "ActionResult.Success")),
        Cap("control.return", BlockCategory.Control, "return {value}",
            "Returns a value from a procedure.", Plain("return {value};", "plain C# (procedure return)"),
            [Any("value")]),
        Cap("control.finish-success", BlockCategory.Control, "finish: success",
            "Reports the action as succeeded.", Plain("return ActionResult.Success();", "ActionResult.Success")),
        Cap("control.finish-failed", BlockCategory.Control, "finish: failed {code} {message}",
            "Reports the action as failed with one of the SDK's error codes.",
            Plain("return ActionResult.Failed({code}, VisualRuntime.ToText(message));",
                "ActionResult.Failed / ActionErrorCodes"),
            [Text("message", required: false)],
            [Menu("code", "ProviderError",
            [
                "NotConfigured", "NotConnected", "PermissionDenied", "ProviderError", "ProviderRejected",
                "InvalidParameter", "NotFound", "Timeout", "Unavailable",
            ], "error code")]),
        Cap("control.finish-accepted", BlockCategory.Control, "finish: accepted {message}",
            "Reports the action as accepted and still running.",
            Plain("return ActionResult.Accepted(VisualRuntime.ToText(message));", "ActionResult.Accepted"),
            [Text("message", required: false)]),
        Stack("control.throw", BlockCategory.Control, "throw {message}",
            "Fails the invocation with an exception.",
            Plain("throw new InvalidOperationException(VisualRuntime.ToText(message));"),
            [Text("message", def: "The action could not run.")]),

        Modifier("control.comment", BlockCategory.Control, "comment {text}",
            "A note attached to a block. Never emitted as code.", [Text("text", required: false)]),
        Modifier("control.disable", BlockCategory.Control, "disable",
            "Skips this block and everything inside it, in the preview and in the generated code."),

        // Not draggable, and deliberately still in the table: a document can contain one, so the emitter
        // has to resolve it to something that emits a comment instead of reporting an unknown kind and
        // refusing the whole file. See BlocksV1Migration: a migration must never make work disappear.
        Placeholder("legacy.unsupported", BlockCategory.Control, "{legacyType}",
            "A statement type from a build this one does not know. Kept, visible, and skipped by the emitter.",
            Plain("// {legacyType} came from a build this one does not know, so it is skipped.",
                "migration placeholder - nothing in the SDK to cite"),
            [Text("legacyType", required: false, label: "type")]),
    ];

    private static IReadOnlyList<BlockDescriptor> DeckRows() =>
    [
        Stack("deck.open-folder", BlockCategory.Deck, "open folder {folder}",
            "Opens a folder on the pressing client.",
            Host("await _integration.Deck.ChangeFolderAsync(VisualRuntime.ToText(folder), context.OriginClientId, context.CancellationToken);",
                "IDeckNavigator.ChangeFolderAsync"),
            [Text("folder", label: "folder id")], capability: "deck", docs: "features/deck"),
        Stack("deck.open-folder-on-client", BlockCategory.Deck, "open folder {folder} on client {client}",
            "Opens a folder on a named client rather than the one that pressed.",
            Host("await _integration.Deck.ChangeFolderAsync(VisualRuntime.ToText(folder), VisualRuntime.ToText(client), context.CancellationToken);",
                "IDeckNavigator.ChangeFolderAsync"),
            [Text("folder"), Text("client")], capability: "deck", docs: "features/deck"),
        Stack("deck.go-to-parent", BlockCategory.Deck, "go to parent folder",
            "Moves the pressing client up one level.",
            Host("await _integration.Deck.GoToParentAsync(context.OriginClientId, context.CancellationToken);",
                "IDeckNavigator.GoToParentAsync"),
            capability: "deck", docs: "features/deck"),
        Stack("deck.go-back", BlockCategory.Deck, "go back",
            "Returns the pressing client to the previously shown folder.",
            Host("await _integration.Deck.GoBackAsync(context.OriginClientId, context.CancellationToken);",
                "IDeckNavigator.GoBackAsync"),
            capability: "deck", docs: "features/deck"),
        Stack("deck.switch-profile", BlockCategory.Deck, "switch profile {profile}",
            "Switches the pressing client to a profile's start folder.",
            Host("await _integration.Deck.ChangeProfileAsync(VisualRuntime.ToText(profile), context.OriginClientId, context.CancellationToken);",
                "IDeckNavigator.ChangeProfileAsync"),
            [Text("profile", label: "profile id")], capability: "deck", docs: "features/deck"),
        Stack("deck.invalidate-icon", BlockCategory.Deck, "invalidate icon {action}",
            "Asks the host to fetch an action's icon again.",
            Host("await _integration.Widgets.InvalidateIconAsync(VisualRuntime.ToText(action), context.CancellationToken);",
                "IWidgetApi.InvalidateIconAsync"),
            [Text("action", label: "action id")],
            capability: "button-icons"),
        Stack("deck.set-button-state", BlockCategory.Deck, "set button state of {widget} to {state}",
            "Changes a widget's state, which is how a button shows on, off or muted.",
            Host("await _integration.Widgets.SetStateAsync(VisualRuntime.ToText(widget), VisualRuntime.ToText(state), context.CancellationToken);",
                "IWidgetApi.SetStateAsync"),
            [Text("widget", label: "widget id"), Text("state", label: "state id")],
            capability: "button-states"),

        Reporter("deck.current-folder", BlockCategory.Deck, "current folder",
            "The folder the pressing client has open.",
            Host("_integration.Deck.GetClients().FirstOrDefault(_c => _c.ClientId == context.OriginClientId)?.FolderId",
                "IDeckNavigator.GetClients / DeckClient.FolderId"), capability: "deck"),
        Reporter("deck.current-profile", BlockCategory.Deck, "current profile",
            "The profile the pressing client is using.",
            Host("_integration.Deck.GetClients().FirstOrDefault(_c => _c.ClientId == context.OriginClientId)?.ProfileId",
                "IDeckNavigator.GetClients / DeckClient.ProfileId"), capability: "deck"),
        Reporter("deck.folder-of-client", BlockCategory.Deck, "folder of client {client}",
            "The folder a named client has open.",
            Host("_integration.Deck.GetClients().FirstOrDefault(_c => _c.ClientId == VisualRuntime.ToText(client))?.FolderId",
                "IDeckNavigator.GetClients / DeckClient.FolderId"),
            [Text("client")], capability: "deck"),
        Reporter("deck.client-count", BlockCategory.Deck, "connected client count",
            "How many clients are connected.",
            Host("_integration.Deck.GetClients().Count", "IDeckNavigator.GetClients"), capability: "deck"),
        Reporter("deck.connected-clients", BlockCategory.Deck, "connected clients",
            "The ids of every connected client.",
            Host("VisualRuntime.List(_integration.Deck.GetClients().Select(_c => _c.ClientId))",
                "IDeckNavigator.GetClients / DeckClient.ClientId"), capability: "deck"),
        Boolean("deck.is-client-connected", BlockCategory.Deck, "is client {client} connected",
            "Whether a named client is connected.",
            Host("_integration.Deck.GetClients().Any(_c => _c.ClientId == VisualRuntime.ToText(client))",
                "IDeckNavigator.GetClients"),
            [Text("client")], capability: "deck"),
    ];

    private static IReadOnlyList<BlockDescriptor> UiRows() =>
    [
        Stack("ui.notify", BlockCategory.Ui, "notify {title} {message}",
            "Shows a notification.",
            Host("_integration.Notifications.Notify(new MacroDeck.Sdk.Notifications.UserNotificationRequest { Title = VisualRuntime.ToText(title), Message = VisualRuntime.ToText(message) });",
                "IUserNotifier.Notify / UserNotificationRequest"),
            [Text("title", def: "Done"), Text("message", def: "The action finished.")]),
        Stack("ui.notify-level", BlockCategory.Ui, "notify {level} {title} {message}",
            "Shows a notification at a chosen level.",
            Host("_integration.Notifications.Notify(new MacroDeck.Sdk.Notifications.UserNotificationRequest { Level = MacroDeck.Sdk.Notifications.UserNotificationLevel.{level}, Title = VisualRuntime.ToText(title), Message = VisualRuntime.ToText(message) });",
                "IUserNotifier.Notify / UserNotificationLevel"),
            [Text("title"), Text("message")],
            [Menu("level", "Info", ["Info", "Warning", "Error"], "level")]),
        Stack("ui.notify-key", BlockCategory.Ui, "notify {key} {title} {message}",
            "Shows a notification that replaces the previous one carrying the same key.",
            Host("_integration.Notifications.Notify(new MacroDeck.Sdk.Notifications.UserNotificationRequest { Key = VisualRuntime.ToText(key), Title = VisualRuntime.ToText(title), Message = VisualRuntime.ToText(message) });",
                "IUserNotifier.Notify / UserNotificationRequest.Key"),
            [Text("key"), Text("title"), Text("message")]),
        Stack("ui.clear-notification", BlockCategory.Ui, "clear notification {key}",
            "Dismisses the notification with this key.",
            Host("_integration.Notifications.Dismiss(VisualRuntime.ToText(key));", "IUserNotifier.Dismiss"),
            [Text("key")]),
        Stack("ui.show-modal", BlockCategory.Ui, "show modal {view} {title}",
            "Asks the pressing client a question, using a view the plugin serves.",
            Interaction("await context.Ui.ShowModalAsync(context.OriginClientId, new MacroDeck.Sdk.Ui.ModalDefinition { ViewId = VisualRuntime.ToText(view), Title = VisualRuntime.ToText(title) }, context.CancellationToken);",
                "IUiInteractions.ShowModalAsync / ModalDefinition.ViewId, .Title"),
            [Text("view", label: "view id"), Text("title", required: false)],
            capability: "macrodeck-ui", docs: "ui/index"),
        Stack("ui.show-modal-data", BlockCategory.Ui, "show modal {view} {title} with {data}",
            "Asks a question and hands the view some context.",
            Interaction("await context.Ui.ShowModalAsync(context.OriginClientId, new MacroDeck.Sdk.Ui.ModalDefinition { ViewId = VisualRuntime.ToText(view), Title = VisualRuntime.ToText(title), Data = VisualRuntime.Data(VisualRuntime.ToText(data)) }, context.CancellationToken);",
                "IUiInteractions.ShowModalAsync / ModalDefinition.Data"),
            [Text("view"), Text("title", required: false), Text("data", required: false)],
            capability: "macrodeck-ui"),
        Reporter("ui.modal-result", BlockCategory.Ui, "result of {view}",
            "The value the user chose, from a modal that returns one.",
            Interaction("await context.Ui.ShowModalAsync<string>(context.OriginClientId, new MacroDeck.Sdk.Ui.ModalDefinition { ViewId = VisualRuntime.ToText(view) }, context.CancellationToken)",
                "IUiInteractions.ShowModalAsync<T> / ModalDefinition.ViewId / ModalResult<T>.Value"),
            [Text("view")], capability: "macrodeck-ui"),
        Stack("ui.log", BlockCategory.Ui, "log {level} {template}",
            "Writes to the Macro Deck log. {name} holes are filled from the action's parameters.",
            Host("_logger.{level}(VisualRuntime.LogTemplate(template, context.Parameters));",
                "Serilog.ILogger (injected) / ActionExecutionContext.Parameters"),
            [Text("template", def: "Action ran")],
            [Menu("level", "Information", ["Verbose", "Debug", "Information", "Warning", "Error"], "level")],
            capability: "logging"),
        Stack("ui.log-with-param", BlockCategory.Ui, "log {level} {template} with {param}",
            "Writes to the log and attaches one parameter as a structured value.",
            Host("_logger.{level}(VisualRuntime.LogTemplate(template, context.Parameters), VisualRuntime.ToText(VisualRuntime.Parameter(context, VisualRuntime.ToText(param))));",
                "Serilog.ILogger (injected) / ActionExecutionContext.Parameters"),
            [Text("template"), Pick("param", SlotType.Parameter, "parameter")],
            [Menu("level", "Information", ["Verbose", "Debug", "Information", "Warning", "Error"], "level")],
            capability: "logging"),
        Stack("ui.update-widget", BlockCategory.Ui, "update widget {widget}",
            "Applies an appearance change to a widget and asks the host to redraw it.",
            Host("await _integration.Widgets.ApplyAsync(new MacroDeck.Sdk.Widgets.WidgetAppearanceRequest { WidgetId = VisualRuntime.ToText(widget) }, context.CancellationToken);",
                "IWidgetApi.ApplyAsync / WidgetAppearanceRequest.WidgetId"),
            [Text("widget", label: "widget id")], capability: "widget-types"),
        Stack("ui.invalidate-widget-icon", BlockCategory.Ui, "invalidate widget icon {widget}",
            "Asks the host to fetch a widget's icon again.",
            Host("await _integration.Widgets.InvalidateIconAsync(VisualRuntime.ToText(widget), context.CancellationToken);",
                "IWidgetApi.InvalidateIconAsync"),
            [Text("widget", label: "widget id")], capability: "widget-types"),
        Boolean("ui.widget-exists", BlockCategory.Ui, "widget {widget} exists",
            "Whether the host knows this widget id.",
            Host("_integration.Widgets.Exists(VisualRuntime.ToText(widget))", "IWidgetApi.Exists"),
            [Text("widget", label: "widget id")], capability: "widget-types"),
        Stack("ui.upload-asset", BlockCategory.Ui, "upload asset {name} from {path}",
            "Registers a file as a UI resource the plugin can serve.",
            Host("await VisualRuntime.RegisterAssetAsync(_integration, VisualRuntime.ToText(name), VisualRuntime.ToText(path), context.CancellationToken);",
                "IUiResourceRegistry.RegisterAsync"),
            [Text("name"), Text("path", label: "file path")], capability: "macrodeck-ui"),
        Stack("ui.pick-item", BlockCategory.Ui, "ask the user to pick an item for {instance}",
            "Shows the host's item picker for one of the plugin's own players.",
            Interaction("context.Interactions.RequestItemPicker(context.OriginClientId, VisualRuntime.ToText(instance), MacroDeck.Sdk.MusicPlayer.MusicPlayerCatalogItemKind.Track, VisualRuntime.ToText(prompt));",
                "IActionInteractions.RequestItemPicker"),
            [Text("instance", label: "player instance id"), Text("prompt", required: false)],
            capability: "music-players"),
        Stack("ui.pick-device", BlockCategory.Ui, "ask the user to pick a device for {instance}",
            "Shows the host's device picker for one of the plugin's own players.",
            Interaction("context.Interactions.RequestDevicePicker(context.OriginClientId, VisualRuntime.ToText(instance), false, VisualRuntime.ToText(prompt));",
                "IActionInteractions.RequestDevicePicker"),
            [Text("instance"), Text("prompt", required: false)], capability: "music-players"),
    ];

    private static IReadOnlyList<BlockDescriptor> EventRows() =>
    [
        Stack("events.publish", BlockCategory.Events, "publish event {event}",
            "Raises one of the plugin's declared events.",
            Host("_integration.Events.Publish(VisualRuntime.ToText(@event), null);", "IEventPublisher.Publish"),
            [Pick("event", SlotType.Event, "event")], capability: "events", docs: "features/events"),
        Stack("events.publish-with-payload", BlockCategory.Events, "publish event {event} with {payload}",
            "Raises a declared event with a payload, written one name=value per line.",
            Host("_integration.Events.Publish(VisualRuntime.ToText(@event), VisualRuntime.Parameters(VisualRuntime.ToText(payload)));",
                "IEventPublisher.Publish"),
            [Pick("event", SlotType.Event, "event"), Text("payload", required: false)],
            capability: "events", docs: "features/events"),
        Stack("events.send-message", BlockCategory.Events, "send message {topic} {body}",
            "Publishes to a message topic other integrations can listen on.",
            Host("await _integration.Messages.PublishAsync(VisualRuntime.ToText(topic), VisualRuntime.Json(VisualRuntime.ToText(body)), context.CancellationToken);",
                "IMessageChannel.PublishAsync"),
            [Text("topic", def: "my.topic"), Text("body", required: false)],
            capability: "messaging", docs: "features/messaging"),
        Reporter("events.request-message", BlockCategory.Events, "request {topic} with {body}",
            "Sends a request on a topic and waits for a reply.",
            Host("await _integration.Messages.RequestAsync(VisualRuntime.ToText(topic), VisualRuntime.Json(VisualRuntime.ToText(body)), System.TimeSpan.FromMilliseconds(VisualRuntime.ToNumber(timeoutMs)), context.CancellationToken)",
                "IMessageChannel.RequestAsync"),
            [Text("topic"), Text("body", required: false), Num("timeoutMs", required: false, def: "5000")],
            capability: "messaging"),
    ];

    private static IReadOnlyList<BlockDescriptor> SensingRows() =>
    [
        Reporter("parameter.get", BlockCategory.Sensing, "parameter {name}",
            "Reads one of the action's configured parameters.",
            Host("VisualRuntime.Parameter(context, VisualRuntime.ToText(name))",
                "ActionExecutionContext.Parameters"),
            [Pick("name", SlotType.Parameter, "parameter")]),
        Reporter("parameter.get-or", BlockCategory.Sensing, "parameter {name} or {fallback}",
            "Reads a parameter, falling back when it is missing or blank.",
            Host("VisualRuntime.Parameter(context, VisualRuntime.ToText(name), VisualRuntime.ToText(fallback))",
                "ActionExecutionContext.Parameters"),
            [Pick("name", SlotType.Parameter, "parameter"), Text("fallback", required: false)]),
        Boolean("parameter.exists", BlockCategory.Sensing, "parameter {name} exists",
            "Whether the action was given this parameter.",
            Host("context.Parameters.ContainsKey(VisualRuntime.ToText(name))",
                "ActionExecutionContext.Parameters"),
            [Pick("name", SlotType.Parameter, "parameter")]),

        Reporter("sensing.get-host-variable", BlockCategory.Sensing, "host variable {name}",
            "Reads a variable the plugin declares.",
            Host("await VisualRuntime.HostVariableAsync(_integration, VisualRuntime.ToText(name), context.CancellationToken)",
                "IVariableApi.GetByNameAsync / VariableHandle.Value (a missing name throws, so the helper maps it to null)"),
            [Pick("name", SlotType.HostVariable, "variable")],
            capability: "variables", docs: "features/variables"),
        Boolean("sensing.host-variable-exists", BlockCategory.Sensing, "host variable {name} exists",
            "Whether the plugin declares this variable.",
            Host("await VisualRuntime.HostVariableAsync(_integration, VisualRuntime.ToText(name), context.CancellationToken) is not null",
                "IVariableApi.GetByNameAsync (throws when absent: the helper maps that to null)"),
            [Pick("name", SlotType.HostVariable, "variable")], capability: "variables"),
        Stack("sensing.set-host-variable", BlockCategory.Sensing, "set host variable {name} to {value}",
            "Writes a user variable, creating it when it does not exist yet.",
            Host("await VisualRuntime.WriteUserVariableAsync(_integration, VisualRuntime.ToText(name), context.OwnerWidgetId, MacroDeck.Sdk.Variables.UserVariableOperation.Set, VisualRuntime.ToText(value), context.CancellationToken);",
                "IUserVariableApi.ApplyAsync / UserVariableOperation.Set"),
            [Pick("name", SlotType.UserVariable, "variable"), Any("value")],
            capability: "variables", docs: "features/variables"),
        Stack("sensing.change-host-variable", BlockCategory.Sensing, "change host variable {name} by {amount}",
            "Adds to a numeric user variable.",
            Host("await VisualRuntime.WriteUserVariableAsync(_integration, VisualRuntime.ToText(name), context.OwnerWidgetId, MacroDeck.Sdk.Variables.UserVariableOperation.Add, VisualRuntime.ToText(amount), context.CancellationToken);",
                "IUserVariableApi.ApplyAsync / UserVariableOperation.Add"),
            [Pick("name", SlotType.UserVariable, "variable"), Num("amount", def: "1")], capability: "variables"),
        Stack("sensing.toggle-host-variable", BlockCategory.Sensing, "toggle host variable {name}",
            "Flips a boolean user variable.",
            Host("await VisualRuntime.WriteUserVariableAsync(_integration, VisualRuntime.ToText(name), context.OwnerWidgetId, MacroDeck.Sdk.Variables.UserVariableOperation.Toggle, null, context.CancellationToken);",
                "IUserVariableApi.ApplyAsync / UserVariableOperation.Toggle"),
            [Pick("name", SlotType.UserVariable, "variable")], capability: "variables"),
        Stack("sensing.append-host-variable", BlockCategory.Sensing, "append {value} to host variable {name}",
            "Appends text to a user variable.",
            Host("await VisualRuntime.WriteUserVariableAsync(_integration, VisualRuntime.ToText(name), context.OwnerWidgetId, MacroDeck.Sdk.Variables.UserVariableOperation.Append, VisualRuntime.ToText(value), context.CancellationToken);",
                "IUserVariableApi.ApplyAsync / UserVariableOperation.Append"),
            [Pick("name", SlotType.UserVariable, "variable"), Text("value")], capability: "variables"),

        Reporter("sensing.get-setting", BlockCategory.Sensing, "setting {key} of {entry}",
            "Reads a value from one of the plugin's configuration entries.",
            Host("await _integration.Config.GetStringAsync(VisualRuntime.EntryId(entry), VisualRuntime.ToText(key), context.CancellationToken)",
                "IIntegrationConfig.GetStringAsync"),
            [Text("key"), Pick("entry", SlotType.ConfigEntry, "config entry")], capability: "config-flows"),
        Stack("sensing.set-setting", BlockCategory.Sensing, "set setting {key} of {entry} to {value}",
            "Writes a value into a configuration entry.",
            Host("await _integration.Config.SetStringAsync(VisualRuntime.EntryId(entry), VisualRuntime.ToText(key), VisualRuntime.ToText(value), context.CancellationToken);",
                "IIntegrationConfig.SetStringAsync"),
            [Text("key"), Pick("entry", SlotType.ConfigEntry, "config entry"), Text("value")],
            capability: "config-flows"),

        Reporter("sensing.timer", BlockCategory.Sensing, "timer",
            "Seconds since this action invocation began.",
            Plain("VisualRuntime.ElapsedSeconds()", "generated runtime")),
        Stack("sensing.reset-timer", BlockCategory.Sensing, "reset timer",
            "Restarts this invocation's timer.", Plain("VisualRuntime.ResetTimer();", "generated runtime")),
        Reporter("sensing.uptime", BlockCategory.Sensing, "uptime",
            "Seconds the plugin process has been running.",
            Plain("VisualRuntime.UptimeSeconds()", "generated runtime")),
        Reporter("sensing.current", BlockCategory.Sensing, "current {part}",
            "A part of the current date or time.",
            Plain("VisualRuntime.Current(VisualRuntime.ToText(part))", "generated runtime"),
            menus: [Menu("part", "Time",
            [
                "Year", "Month", "Day", "Weekday", "Hour", "Minute", "Second",
                "Date", "Time", "Timestamp", "UtcHour", "UtcDate",
            ], "part")]),
        Reporter("sensing.format-date", BlockCategory.Sensing, "format date {value} as {pattern}",
            "Formats a date with an invariant pattern.",
            Plain("VisualRuntime.FormatDate(value, VisualRuntime.ToText(pattern))", "generated runtime"),
            [Any("value"), Text("pattern", def: "yyyy-MM-dd HH:mm")]),
        Reporter("sensing.seconds-since", BlockCategory.Sensing, "seconds since {value}",
            "Seconds between a date and now.",
            Plain("VisualRuntime.SecondsSince(value)", "generated runtime"), [Any("value")]),

        Reporter("sensing.origin-client-id", BlockCategory.Sensing, "origin client id",
            "The client that pressed the button.", Plain("context.OriginClientId", "ActionExecutionContext.OriginClientId")),
        Reporter("sensing.origin-widget-id", BlockCategory.Sensing, "origin widget id",
            "The widget that owns this action, when one does.",
            Plain("context.OwnerWidgetId", "ActionExecutionContext.OwnerWidgetId")),
        Reporter("sensing.action-id", BlockCategory.Sensing, "action id",
            "This action's own id.", Plain("VisualRuntime.ActionId()", "generated runtime")),
        Boolean("sensing.session-established", BlockCategory.Sensing, "a host session is established",
            "Whether the plugin is connected to Macro Deck.",
            new SdkMapping("_integration is not null", "IIntegrationContext (null until the session is established)",
                SuppressHostGuard: true)),
        Stack("sensing.run-script", BlockCategory.Sensing, "run host script {script}",
            "Runs one of the plugin's host scripts.",
            Host("await _integration.Scripts.RunAsync(VisualRuntime.ToText(script), null, context.OriginClientId, context.OwnerWidgetId, context.CancellationToken);",
                "IScriptApi.RunAsync"),
            [Pick("script", SlotType.Script, "script")], capability: "actions"),
        Stack("sensing.run-script-with-inputs", BlockCategory.Sensing, "run host script {script} with {inputs}",
            "Runs a host script with named inputs, one input=parameter per line.",
            Host("await _integration.Scripts.RunAsync(VisualRuntime.ToText(script), VisualRuntime.Parameters(VisualRuntime.ToText(inputs)), context.OriginClientId, context.OwnerWidgetId, context.CancellationToken);",
                "IScriptApi.RunAsync"),
            [Pick("script", SlotType.Script, "script"), Text("inputs", required: false)],
            capability: "actions"),
    ];

    private static IReadOnlyList<BlockDescriptor> OperatorRows() =>
    [
        Reporter("ops.add", BlockCategory.Operators, "{a} + {b}", "Adds two numbers.",
            Plain("VisualRuntime.ToNumber(a) + VisualRuntime.ToNumber(b)"), [Any("a"), Any("b")]),
        Reporter("ops.subtract", BlockCategory.Operators, "{a} - {b}", "Subtracts two numbers.",
            Plain("VisualRuntime.ToNumber(a) - VisualRuntime.ToNumber(b)"), [Any("a"), Any("b")]),
        Reporter("ops.multiply", BlockCategory.Operators, "{a} x {b}", "Multiplies two numbers.",
            Plain("VisualRuntime.ToNumber(a) * VisualRuntime.ToNumber(b)"), [Any("a"), Any("b")]),
        Reporter("ops.divide", BlockCategory.Operators, "{a} / {b}",
            "Divides two numbers. Division by zero yields zero rather than throwing.",
            Plain("VisualRuntime.Divide(a, b)"), [Any("a"), Any("b")]),
        Reporter("ops.modulo", BlockCategory.Operators, "{a} mod {b}", "The remainder of a division.",
            Plain("VisualRuntime.Modulo(a, b)"), [Any("a"), Any("b")]),
        Reporter("ops.round", BlockCategory.Operators, "round {value}", "Rounds to the nearest whole number.",
            Plain("VisualRuntime.Round(value)"), [Any("value")]),
        Reporter("ops.math", BlockCategory.Operators, "{fn} of {value}", "One of the usual maths functions.",
            Plain("VisualRuntime.Math(VisualRuntime.ToText(fn), value)"), [Any("value")],
            [Menu("fn", "abs",
            [
                "abs", "floor", "ceiling", "sqrt", "sin", "cos", "tan",
                "asin", "acos", "atan", "ln", "log", "exp", "pow10",
            ], "function")]),
        Reporter("ops.clamp", BlockCategory.Operators, "clamp {value} between {low} and {high}",
            "Limits a number to a range.", Plain("VisualRuntime.Clamp(value, low, high)"),
            [Any("value"), Any("low"), Any("high")]),
        Reporter("ops.random", BlockCategory.Operators, "random {from} to {to}",
            "A whole number in a range, inclusive.",
            Plain("VisualRuntime.Random(from, to)"), [Any("from", def: "1"), Any("to", def: "10")]),
        Reporter("ops.random-item", BlockCategory.Operators, "random item of {list}",
            "One item of a list, chosen at random.", Plain("VisualRuntime.RandomItem(list)"),
            [ListSlot("list")]),

        Boolean("ops.compare", BlockCategory.Operators, "{a} {op} {b}", "Compares two values.",
            Plain("VisualRuntime.Compare(a, VisualRuntime.ToText(op), b)"),
            [Any("a"), Any("b", required: false)],
            [Menu("op", "=",
            [
                "=", "!=", "<", ">", "<=", ">=",
                "isEmpty", "isNotEmpty", "isAvailable", "isNotAvailable", "contains", "notContains",
            ], "comparison")]),
        Boolean("ops.and", BlockCategory.Operators, "{a} and {b}", "True when both are true.",
            Plain("VisualRuntime.ToBool(a) && VisualRuntime.ToBool(b)"), [Bool("a"), Bool("b")]),
        Boolean("ops.or", BlockCategory.Operators, "{a} or {b}", "True when either is true.",
            Plain("VisualRuntime.ToBool(a) || VisualRuntime.ToBool(b)"), [Bool("a"), Bool("b")]),
        Boolean("ops.not", BlockCategory.Operators, "not {a}", "Inverts a condition.",
            Plain("!VisualRuntime.ToBool(a)"), [Bool("a")]),

        Reporter("ops.join", BlockCategory.Operators, "join {a} {b}", "Joins two values as text.",
            Plain("VisualRuntime.ToText(a) + VisualRuntime.ToText(b)"), [Any("a"), Any("b")]),
        Reporter("ops.join-list", BlockCategory.Operators, "join {list} with {separator}",
            "Joins a list into one piece of text.",
            Plain("VisualRuntime.JoinList(list, VisualRuntime.ToText(separator))"),
            [ListSlot("list"), Text("separator", def: ", ")]),
        Reporter("ops.letter-of", BlockCategory.Operators, "letter {index} of {text}",
            "One character of a value.", Plain("VisualRuntime.LetterOf(index, text)"),
            [Any("index", def: "1"), Any("text")]),
        Reporter("ops.length-of", BlockCategory.Operators, "length of {text}", "How long a value is.",
            Plain("VisualRuntime.ToText(text).Length"), [Any("text")]),
        Boolean("ops.contains", BlockCategory.Operators, "{text} contains {part}",
            "Whether text contains a part.",
            Plain("VisualRuntime.ToText(text).Contains(VisualRuntime.ToText(part), StringComparison.Ordinal)"),
            [Any("text"), Any("part")]),
        Reporter("ops.substring", BlockCategory.Operators, "substring of {text} from {start} length {length}",
            "Part of a value.", Plain("VisualRuntime.Substring(text, start, length)"),
            [Any("text"), Any("start", def: "1"), Any("length", def: "1")]),
        Reporter("ops.replace", BlockCategory.Operators, "replace {find} with {replace} in {text}",
            "Replaces every occurrence.",
            Plain("VisualRuntime.ToText(text).Replace(VisualRuntime.ToText(find), VisualRuntime.ToText(replace), StringComparison.Ordinal)"),
            [Any("find"), Any("replace"), Any("text")]),
        Reporter("ops.upper", BlockCategory.Operators, "uppercase {text}", "Upper-cases a value.",
            Plain("VisualRuntime.ToText(text).ToUpperInvariant()"), [Any("text")]),
        Reporter("ops.lower", BlockCategory.Operators, "lowercase {text}", "Lower-cases a value.",
            Plain("VisualRuntime.ToText(text).ToLowerInvariant()"), [Any("text")]),
        Reporter("ops.trim", BlockCategory.Operators, "trim {text}", "Removes leading and trailing spaces.",
            Plain("VisualRuntime.ToText(text).Trim()"), [Any("text")]),
        Reporter("ops.split", BlockCategory.Operators, "split {text} by {separator}",
            "Splits text into a list.", Plain("VisualRuntime.Split(text, VisualRuntime.ToText(separator))"),
            [Any("text"), Text("separator", def: ",")]),
        Reporter("ops.format", BlockCategory.Operators, "format {template} with {args}",
            "Fills {0}, {1}, ... holes in a template.",
            Plain("VisualRuntime.Format(VisualRuntime.ToText(template), VisualRuntime.ToText(args))"),
            [Text("template"), Text("args", required: false)]),
        Reporter("ops.url-encode", BlockCategory.Operators, "url encode {text}", "Percent-encodes a value.",
            Plain("Uri.EscapeDataString(VisualRuntime.ToText(text))"), [Any("text")]),
        Reporter("ops.base64-encode", BlockCategory.Operators, "base64 encode {text}", "Base64-encodes text.",
            Plain("Convert.ToBase64String(System.Text.Encoding.UTF8.GetBytes(VisualRuntime.ToText(text)))"),
            [Any("text")]),
        Reporter("ops.base64-decode", BlockCategory.Operators, "base64 decode {text}", "Decodes base64 text.",
            Plain("VisualRuntime.Base64Decode(VisualRuntime.ToText(text))"), [Any("text")]),
        Reporter("ops.json-get", BlockCategory.Operators, "json get {path} from {text}",
            "Reads a value out of JSON with a dotted path.",
            Plain("VisualRuntime.JsonGet(VisualRuntime.ToText(text), VisualRuntime.ToText(path))"),
            [Text("path"), Any("text")]),
    ];

    private static IReadOnlyList<BlockDescriptor> VariableRows() =>
    [
        Stack("var.set", BlockCategory.Variables, "set {var} to {value}",
            "Sets one of this script's variables.",
            Plain("VisualRuntime.Set(VisualRuntime.ToText(var), value);"),
            [Pick("var", SlotType.Variable, "variable"), Any("value")]),
        Stack("var.change", BlockCategory.Variables, "change {var} by {amount}", "Adds to a variable.",
            Plain("VisualRuntime.Change(VisualRuntime.ToText(var), amount);"),
            [Pick("var", SlotType.Variable, "variable"), Any("amount", def: "1")]),
        Stack("var.set-from-parameter", BlockCategory.Variables, "set {var} from parameter {param}",
            "Reads a parameter into a typed local, failing when it is required and missing.",
            Host("VisualRuntime.Set(VisualRuntime.ToText(var), VisualRuntime.ReadParameter(context, VisualRuntime.ToText(param), VisualRuntime.ToText(type), VisualRuntime.ToBool(required)));",
                "ActionExecutionContext.Parameters"),
            [Pick("var", SlotType.Variable, "variable"), Pick("param", SlotType.Parameter, "parameter")],
            [Menu("type", "Text", ["Text", "Numeric", "Boolean"], "type"),
             Menu("required", "false", ["true", "false"], "required?")]),
        Stack("var.set-from-host", BlockCategory.Variables, "set {var} from host variable {name}",
            "Reads a host variable into a local.",
            Host("VisualRuntime.Set(VisualRuntime.ToText(var), await VisualRuntime.HostVariableAsync(_integration, VisualRuntime.ToText(name), context.CancellationToken));",
                "IVariableApi.GetByNameAsync / VariableHandle.Value"),
            [Pick("var", SlotType.Variable, "variable"), Pick("name", SlotType.HostVariable, "host variable")],
            capability: "variables"),
        Reporter("var.get", BlockCategory.Variables, "{var}", "Reads one of this script's variables.",
            Plain("VisualRuntime.Get(var)"),
            [Pick("var", SlotType.Variable, "variable")]),
        Stack("var.watch", BlockCategory.Variables, "watch {var}",
            "Shows a variable in the debugger's watch table.",
            Plain("VisualRuntime.Watch(VisualRuntime.ToText(var));"),
            [Pick("var", SlotType.Variable, "variable")]),
        Stack("var.unwatch", BlockCategory.Variables, "unwatch {var}",
            "Removes a variable from the watch table.",
            Plain("VisualRuntime.Unwatch(VisualRuntime.ToText(var));"),
            [Pick("var", SlotType.Variable, "variable")]),
        Stack("var.clear", BlockCategory.Variables, "clear my variables",
            "Forgets every local this script declared.", Plain("VisualRuntime.ClearLocals();")),
    ];

    private static IReadOnlyList<BlockDescriptor> ListRows() =>
    [
        Stack("list.define", BlockCategory.Lists, "define list {name}", "Declares a list for this script.",
            Plain("var {name} = new List<string>();"), [Pick("name", SlotType.List, "list")]),
        Stack("list.add", BlockCategory.Lists, "add {item} to {list}", "Appends an item.",
            Plain("VisualRuntime.List(list).Add(VisualRuntime.ToText(item));"), [Any("item"), ListSlot("list")]),
        Stack("list.delete", BlockCategory.Lists, "delete {index} of {list}", "Removes one item.",
            Plain("VisualRuntime.List(list).RemoveAt((int)VisualRuntime.ToNumber(index) - 1);"),
            [Any("index", def: "1"), ListSlot("list")]),
        Stack("list.clear", BlockCategory.Lists, "delete all of {list}", "Removes every item.",
            Plain("VisualRuntime.List(list).Clear();"), [ListSlot("list")]),
        Stack("list.insert", BlockCategory.Lists, "insert {item} at {index} of {list}",
            "Inserts an item at a position.",
            Plain("VisualRuntime.List(list).Insert((int)VisualRuntime.ToNumber(index) - 1, VisualRuntime.ToText(item));"),
            [Any("item"), Any("index", def: "1"), ListSlot("list")]),
        Stack("list.replace", BlockCategory.Lists, "replace item {index} of {list} with {item}",
            "Replaces one item.",
            Plain("VisualRuntime.List(list)[(int)VisualRuntime.ToNumber(index) - 1] = VisualRuntime.ToText(item);"),
            [Any("index", def: "1"), ListSlot("list"), Any("item")]),
        Stack("list.join", BlockCategory.Lists, "join {source} to {target}",
            "Appends every item of one list to another.",
            Plain("VisualRuntime.List(target).AddRange(VisualRuntime.List(source));"),
            [ListSlot("source"), ListSlot("target")]),
        Stack("list.sort", BlockCategory.Lists, "sort {list}", "Sorts a list as text, ascending.",
            Plain("VisualRuntime.List(list).Sort(StringComparer.Ordinal);"), [ListSlot("list")]),
        Reporter("list.item", BlockCategory.Lists, "item {index} of {list}", "One item of a list.",
            Plain("VisualRuntime.Item(list, index)"), [Any("index", def: "1"), ListSlot("list")]),
        Reporter("list.index-of", BlockCategory.Lists, "item # of {item} in {list}", "Where an item is.",
            Plain("VisualRuntime.IndexOf(list, item)"), [Any("item"), ListSlot("list")]),
        Reporter("list.length", BlockCategory.Lists, "length of {list}", "How many items a list has.",
            Plain("VisualRuntime.List(list).Count"), [ListSlot("list")]),
        Boolean("list.contains", BlockCategory.Lists, "{list} contains {item}", "Whether a list has an item.",
            Plain("VisualRuntime.List(list).Contains(VisualRuntime.ToText(item), StringComparer.Ordinal)"),
            [ListSlot("list"), Any("item")]),
        Reporter("list.value", BlockCategory.Lists, "{list}", "The whole list.",
            Plain("VisualRuntime.List(list)"), [ListSlot("list")]),
    ];

    private static IReadOnlyList<BlockDescriptor> ParameterRows() =>
    [
        Reporter("data.read-parameter", BlockCategory.Parameters, "read parameter {name} as {type}",
            "Reads a parameter, converting it to a type.",
            Host("VisualRuntime.Convert(VisualRuntime.Parameter(context, VisualRuntime.ToText(name)), VisualRuntime.ToText(type))",
                "ActionExecutionContext.Parameters"),
            [Pick("name", SlotType.Parameter, "parameter")],
            [Menu("type", "Text", ["Text", "Numeric", "Boolean"], "type")]),
        Reporter("data.read-payload", BlockCategory.Parameters, "read payload {name}",
            "Reads a value the host delivered with this invocation.",
            Host("VisualRuntime.Parameter(context, VisualRuntime.ToText(name))",
                "ActionExecutionContext.Parameters"),
            [Pick("name", SlotType.Parameter, "payload")]),
        Boolean("data.parameter-has-value", BlockCategory.Parameters, "parameter {name} has a value",
            "Whether a parameter is present and not blank.",
            Host("VisualRuntime.HasValue(context, VisualRuntime.ToText(name))",
                "ActionExecutionContext.Parameters"),
            [Pick("name", SlotType.Parameter, "parameter")]),
        Reporter("data.to-number", BlockCategory.Parameters, "to number {value}", "Converts a value to a number.",
            Plain("VisualRuntime.ToNumber(value)"), [Any("value")]),
        Reporter("data.to-text", BlockCategory.Parameters, "to text {value}", "Converts a value to text.",
            Plain("VisualRuntime.ToText(value)"), [Any("value")]),
        Reporter("data.to-boolean", BlockCategory.Parameters, "to boolean {value}",
            "Converts a value to a boolean.", Plain("VisualRuntime.ToBool(value)"), [Any("value")]),
        Boolean("data.is-numeric", BlockCategory.Parameters, "is {value} a number",
            "Whether a value parses as a number.", Plain("VisualRuntime.IsNumeric(value)"), [Any("value")]),
        Reporter("data.default-if-empty", BlockCategory.Parameters, "default {value} to {fallback}",
            "Uses a fallback when a value is blank.",
            Plain("VisualRuntime.DefaultIfEmpty(value, fallback)"), [Any("value"), Any("fallback")]),
        Reporter("data.decode-json", BlockCategory.Parameters, "decode json {text}",
            "Turns JSON into a list of values.", Plain("VisualRuntime.DecodeJson(VisualRuntime.ToText(text))"),
            [Any("text")]),
    ];

    private static IReadOnlyList<BlockDescriptor> NetworkRows() =>
    [
        Stack("http.get", BlockCategory.Network, "HTTP GET {url} as {into}",
            "Fetches a URL and keeps the response in a variable.",
            Plain("var {into} = await VisualRuntime.HttpAsync(VisualRuntime.ToText(url), \"GET\", null, null, context.CancellationToken);",
                "System.Net.Http.HttpClient"),
            [Text("url", def: "https://example.com/api"), Text("into", def: "response", label: "into")],
            docs: "features/actions"),
        Stack("http.post", BlockCategory.Network, "HTTP POST {url} body {body} as {into}",
            "Posts a body and keeps the response.",
            Plain("var {into} = await VisualRuntime.HttpAsync(VisualRuntime.ToText(url), \"POST\", VisualRuntime.ToText(body), null, context.CancellationToken);",
                "System.Net.Http.HttpClient"),
            [Text("url"), Text("body", required: false), Text("into", def: "response")]),
        Stack("http.request", BlockCategory.Network, "HTTP {method} {url} with headers {headers} as {into}",
            "Any method, with headers one name=value per line.",
            Plain("var {into} = await VisualRuntime.HttpAsync(VisualRuntime.ToText(url), VisualRuntime.ToText(method), VisualRuntime.ToText(body), VisualRuntime.Parameters(VisualRuntime.ToText(headers)), context.CancellationToken);",
                "System.Net.Http.HttpClient"),
            [Text("url"), Text("headers", required: false), Text("body", required: false),
             Text("into", def: "response")],
            [Menu("method", "GET", ["GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS"], "method")]),
        Stack("http.set-bearer", BlockCategory.Network, "use bearer token from parameter {name}",
            "Adds an Authorization header read from a parameter, never from the document.",
            Plain("VisualRuntime.UseBearerToken(VisualRuntime.ToText(name));",
                "System.Net.Http.Headers.AuthenticationHeaderValue"),
            [Pick("name", SlotType.Parameter, "parameter")]),
        Container("http.retry", BlockCategory.Network, "retry {times} times waiting {ms} ms",
            "Retries the body while the last request failed.",
            Plain("for (var _attempt = 0; _attempt < (int)VisualRuntime.ToNumber(times) && VisualRuntime.LastRequestFailed(); _attempt++)"),
            [Num("times", def: "3"), Num("ms", def: "500")], bodies: [Body("body", "retry")]),
        Reporter("http.response-body", BlockCategory.Network, "response body of {request}",
            "The body of a finished request.", Plain("VisualRuntime.ResponseBody(request)", "generated response record"),
            [Text("request")]),
        Reporter("http.status-code", BlockCategory.Network, "status code of {request}",
            "The HTTP status code of a finished request.",
            Plain("VisualRuntime.StatusCode(request)", "generated response record"), [Text("request")]),
        Reporter("http.response-header", BlockCategory.Network, "response header {name} of {request}",
            "One header of a finished request.",
            Plain("VisualRuntime.ResponseHeader(request, VisualRuntime.ToText(name))", "generated response record"),
            [Text("name"), Text("request")]),
        Boolean("http.is-success", BlockCategory.Network, "response {request} is success",
            "Whether the last request succeeded.",
            Plain("VisualRuntime.IsSuccess(request)", "generated response record"), [Text("request")]),
        Boolean("http.timed-out", BlockCategory.Network, "request {request} timed out",
            "Whether the last request timed out.",
            Plain("VisualRuntime.TimedOut(request)", "generated response record"), [Text("request")]),
        Stack("http.download", BlockCategory.Network, "download {url} to {path}",
            "Writes a URL's body to a file.",
            Plain("await VisualRuntime.DownloadAsync(VisualRuntime.ToText(url), VisualRuntime.ToText(path), context.CancellationToken);",
                "System.Net.Http.HttpClient"),
            [Text("url"), Text("path", label: "file path")]),
        Stack("http.upload", BlockCategory.Network, "upload file {path} to {url}",
            "Posts a file's bytes to a URL.",
            Plain("await VisualRuntime.UploadAsync(VisualRuntime.ToText(path), VisualRuntime.ToText(url), context.CancellationToken);",
                "System.Net.Http.HttpClient"),
            [Text("path", label: "file path"), Text("url")]),
    ];

    private static IReadOnlyList<BlockDescriptor> ProcedureRows() =>
    [
        Hat("proc.define", BlockCategory.Procedures, "define {name}",
            "Defines a procedure, emitted as a local function inside the block region.",
            "plain C# (local function)", [Text("name", def: "myProcedure")]),
        Hat("proc.define-returning", BlockCategory.Procedures, "define {name} returning a value",
            "Defines a procedure that produces a value.",
            "plain C# (local function)", [Text("name", def: "myProcedure")]),
        Stack("proc.call", BlockCategory.Procedures, "call {name}", "Runs a procedure defined in this document.",
            Plain("await VisualRuntime.NoToken() ?? Task.CompletedTask", "emitted by the emitter, not by a template"),
            [Pick("name", SlotType.Procedure, "procedure")]),
        Stack("proc.call-with", BlockCategory.Procedures, "call {name} with {args}",
            "Runs a procedure with arguments.",
            Plain("await VisualRuntime.NoToken() ?? Task.CompletedTask", "emitted by the emitter, not by a template"),
            [Pick("name", SlotType.Procedure, "procedure"), Text("args", required: false)]),
        Reporter("proc.call-value", BlockCategory.Procedures, "{name} with {args}",
            "Runs a procedure that returns a value.",
            Plain("await VisualRuntime.NoToken() ?? Task.CompletedTask", "emitted by the emitter, not by a template"),
            [Pick("name", SlotType.Procedure, "procedure"), Text("args", required: false)]),
    ];
}
